### ISSUE TITLE
Zenodo Archival?

### ISSUE THREAD

**Issue by adswa** [myyoda/poster#3]
Maybe I missed it, but could you archive this poster at Zenodo to make it citable?

**Comment by yarikoptic** [comment]
great idea!  I will just make a release for the entire repo after integrating it with zenodo....

**Comment by yarikoptic** [comment]
hm, although -- we have multiple posters here now.  So better indeed just to create a new dedicated to OHBM poster entry on zenodo -- will try to do that now (never did this manual dance)

**Comment by yarikoptic** [comment]
damn, was almost done with zenodo entry, searched up for title and found https://f1000research.com/posters/7-1965  ;-)

Hanke M, Meyer KA, Visconti di Oleggio Castello M et al. YODA: YODA's Organigram on Data Analysis [version 1; not peer reviewed]. F1000Research 2018, 7:1965 (poster) (https://doi.org/10.7490/f1000research.1116363.1)

```
$> curl -s -L POST -d "" --header "Accept: application/x-bibtex; charset=utf-8" https://doi.org/10.7490/f1000research.1116363.1
@misc{https://doi.org/10.7490/f1000research.1116363.1,
  doi = {10.7490/F1000RESEARCH.1116363.1},
  url = {https://f1000research.com/posters/7-1965},
  author = {Hanke, Michael and Meyer, Kyle A. and Castello, Matteo Visconti Di Oleggio and Poldrack, Benjamin and Halchenko, Yaroslav O.},
  title = {YODA: YODA's Organigram on Data Analysis},
  publisher = {F1000 Research Limited},
  year = {2018}
}
```

**Comment by adswa** [comment]
Oh great, thanks!
